### ISSUE TITLE
Random behaviour

### ISSUE THREAD

**Issue by jvelazqueztraut** [resin-io-projects/resin-wifi-connect-example#1]
I'm getting a random behavious where the AP is not always turned on if the device doesnt have a connection.

Whenever I do have an Ethernet based connection, I constantly get this error:
```
Clear disabled
{ Error: No introspectable at /usr/src/app/resin-wifi-connect/node_modules/dbus/lib/bus.js:101:15
cause: Error: No introspectable at /usr/src/app/resin-wifi-connect/node_modules/dbus/lib/bus.js:101:15, isOperational: true }
```

I'm working on a RPi 3 on a node project.

**Comment by jbaldwinroberts** [comment]
Hey,

I think this was fixed in `v2.0.4` of [resin-wifi-connect](https://github.com/resin-io/resin-wifi-connect/releases/tag/v2.0.4) but I hadn't got round to updating this repository to pull the new version. I will do that now.
